'use client'

import {useEffect} from 'react'
import {getSupabaseBrowserClient} from '../../lib/supabase'

const LANGUAGES=['en','af','zu','xh','st','tn','nso','ts','ss','de','fr','es','pt']

const dict={
 af:{'Workspace':'Werkruimte','Overview':'Oorsig','Subjects':'Vakke','AI Tutor':'KI-tutor','Mock Exams':'Proefeksamens','Daily Tasks':'Daaglikse take','Progress':'Vordering','Settings':'Instellings','Summaries':'Opsommings','Sign out':'Teken uit','Loading':'Laai','Subject':'Vak','Add subject':'Voeg vak by','Manage material':'Bestuur studiemateriaal','Study session':'Studiesessie','New chat':'Nuwe gesprek','Ask TIALO':'Vra TIALO','Choose a subject':'Kies ’n vak','Language':'Taal','Appearance':'Voorkoms','Account':'Rekening','Save':'Stoor','Cancel':'Kanselleer','Today':'Vandag','This week':'Hierdie week','Completed':'Voltooi','Remaining':'Oorblywend','Study plan':'Studieplan','Make today count.':'Maak vandag saak.','Practice with purpose.':'Oefen met doelgerigtheid.','Build your study library.':'Bou jou studiebiblioteek.','Your progress, without the noise.':'Jou vordering, sonder die geraas.'},
 zu:{'Workspace':'Indawo yokusebenza','Overview':'Uhlolojikelele','Subjects':'Izifundo','AI Tutor':'Umfundisi we-AI','Mock Exams':'Izivivinyo zokuzijwayeza','Daily Tasks':'Imisebenzi yansuku zonke','Progress':'Inqubekelaphambili','Settings':'Izilungiselelo','Summaries':'Izifinyezo','Sign out':'Phuma','Subject':'Isifundo','Add subject':'Engeza isifundo','Manage material':'Phatha izinto zokufunda','Study session':'Isikhathi sokufunda','New chat':'Ingxoxo entsha','Ask TIALO':'Buza u-TIALO','Choose a subject':'Khetha isifundo','Language':'Ulimi','Appearance':'Ukubukeka','Account':'I-akhawunti','Save':'Gcina','Cancel':'Khansela','Today':'Namuhla','This week':'Kuleli sonto','Completed':'Kuqediwe','Remaining':'Okusele','Study plan':'Uhlelo lokufunda','Make today count.':'Yenza namuhla kubaluleke.','Practice with purpose.':'Zijwayeze ngenhloso.','Build your study library.':'Yakha umtapo wakho wokufunda.','Your progress, without the noise.':'Inqubekelaphambili yakho, ngaphandle komsindo.'},
 xh:{'Workspace':'Indawo yokusebenza','Overview':'Amagqabantshintshi','Subjects':'Izifundo','AI Tutor':'Umfundisi we-AI','Mock Exams':'Iimviwo zokuziqhelanisa','Daily Tasks':'Imisebenzi yemihla ngemihla','Progress':'Inkqubela','Settings':'Iisetingi','Summaries':'Izishwankathelo','Sign out':'Phuma','Subject':'Isifundo','Add subject':'Yongeza isifundo','Manage material':'Lawula izixhobo zokufunda','Study session':'Iseshoni yokufunda','New chat':'Incoko entsha','Ask TIALO':'Buza u-TIALO','Choose a subject':'Khetha isifundo','Language':'Ulwimi','Appearance':'Inkangeleko','Account':'Iakhawunti','Save':'Gcina','Cancel':'Rhoxisa','Today':'Namhlanje','This week':'Kule veki','Completed':'Kugqityiwe','Remaining':'Okuseleyo','Study plan':'Isicwangciso sokufunda','Make today count.':'Yenza namhlanje kubaluleke.','Practice with purpose.':'Ziqhelanise ngenjongo.','Build your study library.':'Yakha ithala lakho lokufunda.','Your progress, without the noise.':'Inkqubela yakho, ngaphandle kwengxolo.'},
 st:{'Workspace':'Sebaka sa mosebetsi','Overview':'Kakaretso','Subjects':'Dithuto','AI Tutor':'Moruti wa AI','Mock Exams':'Diteko tsa boitlwaetso','Daily Tasks':'Mesebetsi ya letsatsi le letsatsi','Progress':'Tsoelopele','Settings':'Disetting','Summaries':'Dintshwantsho tse kgutshwane','Sign out':'Tsoa','Subject':'Thuto','Add subject':'Eketsa thuto','Manage material':'Laola thepa ya ho ithuta','Study session':'Nako ya ho ithuta','New chat':'Puisano e ntjha','Ask TIALO':'Botsa TIALO','Choose a subject':'Kgetha thuto','Language':'Puo','Appearance':'Ponahalo','Account':'Akhaonto','Save':'Boloka','Cancel':'Hlakola','Today':'Kajeno','This week':'Bekeng ena','Completed':'E phethilwe','Remaining':'E setseng','Study plan':'Moralo wa ho ithuta','Make today count.':'Etsa hore kajeno ho be bohlokwa.','Practice with purpose.':'Itlwaetse ka sepheo.','Build your study library.':'Haha laeborari ya hao ya ho ithuta.','Your progress, without the noise.':'Tsoelopele ya hao, ntle le lerata.'},
 tn:{'Workspace':'Lefelo la tiro','Overview':'Kakaretso','Subjects':'Dithuto','AI Tutor':'Morutisi wa AI','Mock Exams':'Ditlhatlhobo tsa boitlwaetso','Daily Tasks':'Ditiro tsa letsatsi le letsatsi','Progress':'Tswelelopele','Settings':'Dipeakanyo','Summaries':'Dintlha tse di khutshwafaditsweng','Sign out':'Tswa','Subject':'Thuto','Add subject':'Tsenya thuto','Manage material':'Laola didirisiwa tsa go ithuta','Study session':'Thuto','New chat':'Puisano e ntšha','Ask TIALO':'Botsa TIALO','Choose a subject':'Tlhopha thuto','Language':'Puo','Appearance':'Ponalo','Account':'Akhaonto','Save':'Boloka','Cancel':'Khansela','Today':'Gompieno','This week':'Beke eno','Completed':'Go weditswe','Remaining':'Go setseng','Study plan':'Leano la go ithuta','Make today count.':'Dira gore gompieno go nne botlhokwa.','Practice with purpose.':'Ithute ka maikaelelo.','Build your study library.':'Agela laeborari ya gago ya thuto.','Your progress, without the noise.':'Tswelelopele ya gago, ntle le modumo.'},
 nso:{'Workspace':'Lefelo la mošomo','Overview':'Kakaretšo','Subjects':'Dithuto','AI Tutor':'Morutiši wa AI','Mock Exams':'Diteko tša boitlwaetšo','Daily Tasks':'Mešomo ya letšatši le letšatši','Progress':'Tšwelopele','Settings':'Dipeakanyo','Summaries':'Dintlha tša kakaretšo','Sign out':'Tšwa','Subject':'Thuto','Add subject':'Oketša thuto','Manage material':'Laola didirišwa tša go ithuta','Study session':'Seboka sa thuto','New chat':'Poledišano e mpsha','Ask TIALO':'Botšiša TIALO','Choose a subject':'Kgetha thuto','Language':'Leleme','Appearance':'Ponagalo','Account':'Akhaonto','Save':'Boloka','Cancel':'Khansela','Today':'Lehono','This week':'Beke ye','Completed':'Go phethilwe','Remaining':'Tše di šetšego','Study plan':'Leano la thuto','Make today count.':'Dira gore lehono go be bohlokwa.','Practice with purpose.':'Itlwaetše ka maikemišetšo.','Build your study library.':'Aga laeborari ya gago ya thuto.','Your progress, without the noise.':'Tšwelopele ya gago ntle le lešata.'},
 ts:{'Workspace':'Ndhawu yo tirha','Overview':'Nkatsakanyo','Subjects':'Tidyondzo','AI Tutor':'Mudyondzisi wa AI','Mock Exams':'Swikambelo swo titoloveta','Daily Tasks':'Mintirho ya siku na siku','Progress':'Nhluvuko','Settings':'Swilungiselelo','Summaries':'Tinhlamuselo to koma','Sign out':'Humesa','Subject':'Dyondzo','Add subject':'Engetela dyondzo','Manage material':'Lawula swilo swo dyondza','Study session':'Nkarhi wo dyondza','New chat':'Bulo lerintshwa','Ask TIALO':'Vutisa TIALO','Choose a subject':'Hlawula dyondzo','Language':'Ririmi','Appearance':'Mavonelo','Account':'Akhaonto','Save':'Hlayisa','Cancel':'Khansela','Today':'Namuntlha','This week':'Vhiki leri','Completed':'Swi hetiwile','Remaining':'Leswi saleke','Study plan':'Nkunguhato wo dyondza','Make today count.':'Endla leswaku namuntlha ku va ka nkoka.','Practice with purpose.':'Titolovete hi xikongomelo.','Build your study library.':'Aka layiburari ya wena yo dyondza.','Your progress, without the noise.':'Nhluvuko wa wena handle ka mpfumawulo.'},
 ss:{'Workspace':'Indzawo yekusebenta','Overview':'Sishwankatelo','Subjects':'Tifundvo','AI Tutor':'Umfundzisi we-AI','Mock Exams':'Tivivinyo tekutilolonga','Daily Tasks':'Imisebenti yemalanga onkhe','Progress':'Inchubekelembili','Settings':'Tinhlelo','Summaries':'Tifinyeto','Sign out':'Phuma','Subject':'Sifundvo','Add subject':'Ngeta sifundvo','Manage material':'Phatsa tintfo tekufundza','Study session':'Sikhatsi sekufundza','New chat':'Inkhulumo lensha','Ask TIALO':'Buta TIALO','Choose a subject':'Khetsa sifundvo','Language':'Lulwimi','Appearance':'Kubukeka','Account':'I-akhawunti','Save':'Gcina','Cancel':'Khansela','Today':'Lamuhla','This week':'Kuleliviki','Completed':'Kuphelile','Remaining':'Lokusele','Study plan':'Lisu lekufundza','Make today count.':'Yenta lamuhla kube ngulelibalulekile.','Practice with purpose.':'Tilolonge ngenhloso.','Build your study library.':'Yakha umtapo wakho wekufundza.','Your progress, without the noise.':'Inchubekelembili yakho ngaphandle kwemsindvo.'},
 de:{'Workspace':'Arbeitsbereich','Overview':'Übersicht','Subjects':'Fächer','AI Tutor':'KI-Tutor','Mock Exams':'Probeprüfungen','Daily Tasks':'Tägliche Aufgaben','Progress':'Fortschritt','Settings':'Einstellungen','Summaries':'Zusammenfassungen','Sign out':'Abmelden','Subject':'Fach','Add subject':'Fach hinzufügen','Manage material':'Lernmaterial verwalten','Study session':'Lerneinheit','New chat':'Neuer Chat','Ask TIALO':'TIALO fragen','Choose a subject':'Fach auswählen','Language':'Sprache','Appearance':'Erscheinungsbild','Account':'Konto','Save':'Speichern','Cancel':'Abbrechen','Today':'Heute','This week':'Diese Woche','Completed':'Abgeschlossen','Remaining':'Verbleibend','Study plan':'Lernplan','Make today count.':'Mach den heutigen Tag wertvoll.','Practice with purpose.':'Übe mit einem Ziel.','Build your study library.':'Baue deine Lernbibliothek auf.','Your progress, without the noise.':'Dein Fortschritt, ohne Ablenkung.'},
 fr:{'Workspace':'Espace de travail','Overview':'Vue d’ensemble','Subjects':'Matières','AI Tutor':'Tuteur IA','Mock Exams':'Examens blancs','Daily Tasks':'Tâches quotidiennes','Progress':'Progrès','Settings':'Paramètres','Summaries':'Résumés','Sign out':'Se déconnecter','Subject':'Matière','Add subject':'Ajouter une matière','Manage material':'Gérer le matériel','Study session':'Session d’étude','New chat':'Nouvelle discussion','Ask TIALO':'Demander à TIALO','Choose a subject':'Choisir une matière','Language':'Langue','Appearance':'Apparence','Account':'Compte','Save':'Enregistrer','Cancel':'Annuler','Today':"Aujourd’hui",'This week':'Cette semaine','Completed':'Terminé','Remaining':'Restant','Study plan':'Plan d’étude','Make today count.':'Fais de cette journée une réussite.','Practice with purpose.':'Entraîne-toi avec un objectif.','Build your study library.':'Construis ta bibliothèque d’étude.','Your progress, without the noise.':'Ton progrès, sans distraction.'},
 es:{'Workspace':'Espacio de trabajo','Overview':'Resumen','Subjects':'Asignaturas','AI Tutor':'Tutor de IA','Mock Exams':'Exámenes de práctica','Daily Tasks':'Tareas diarias','Progress':'Progreso','Settings':'Configuración','Summaries':'Resúmenes','Sign out':'Cerrar sesión','Subject':'Asignatura','Add subject':'Añadir asignatura','Manage material':'Gestionar material','Study session':'Sesión de estudio','New chat':'Nuevo chat','Ask TIALO':'Preguntar a TIALO','Choose a subject':'Elegir asignatura','Language':'Idioma','Appearance':'Apariencia','Account':'Cuenta','Save':'Guardar','Cancel':'Cancelar','Today':'Hoy','This week':'Esta semana','Completed':'Completado','Remaining':'Pendiente','Study plan':'Plan de estudio','Make today count.':'Haz que hoy cuente.','Practice with purpose.':'Practica con propósito.','Build your study library.':'Construye tu biblioteca de estudio.','Your progress, without the noise.':'Tu progreso, sin ruido.'},
 pt:{'Workspace':'Área de trabalho','Overview':'Visão geral','Subjects':'Disciplinas','AI Tutor':'Tutor de IA','Mock Exams':'Exames simulados','Daily Tasks':'Tarefas diárias','Progress':'Progresso','Settings':'Definições','Summaries':'Resumos','Sign out':'Terminar sessão','Subject':'Disciplina','Add subject':'Adicionar disciplina','Manage material':'Gerir material','Study session':'Sessão de estudo','New chat':'Novo chat','Ask TIALO':'Perguntar ao TIALO','Choose a subject':'Escolher disciplina','Language':'Idioma','Appearance':'Aparência','Account':'Conta','Save':'Guardar','Cancel':'Cancelar','Today':'Hoje','This week':'Esta semana','Completed':'Concluído','Remaining':'Restante','Study plan':'Plano de estudo','Make today count.':'Faz o dia de hoje valer a pena.','Practice with purpose.':'Pratica com propósito.','Build your study library.':'Constrói a tua biblioteca de estudo.','Your progress, without the noise.':'O teu progresso, sem ruído.'}
}

export function getLanguage(){if(typeof window==='undefined')return'en';return localStorage.getItem('tialo-language')||'en'}
export function translate(value,language=getLanguage()){return dict[language]?.[value]||value}

export default function LanguageSync(){
 useEffect(()=>{
  let cancelled=false
  const apply=()=>{
   const lang=getLanguage()
   document.documentElement.lang=lang
   if(lang==='en')return
   const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT)
   const nodes=[]
   while(walker.nextNode())nodes.push(walker.currentNode)
   for(const node of nodes){
    if(cancelled||!node.nodeValue?.trim())continue
    const parent=node.parentElement
    if(!parent||['SCRIPT','STYLE','INPUT','TEXTAREA'].includes(parent.tagName)||parent.closest('[data-no-translate]'))continue
    const raw=node.nodeValue.trim()
    const translated=translate(raw,lang)
    if(translated!==raw)node.nodeValue=node.nodeValue.replace(raw,translated)
   }
  }
  const observer=new MutationObserver(()=>{clearTimeout(window.__tialoTranslateTimer);window.__tialoTranslateTimer=setTimeout(apply,80)})
  observer.observe(document.body,{childList:true,subtree:true})
  apply()
  return()=>{cancelled=true;observer.disconnect()}
 },[])
 return null
}
