'use client'
import {useEffect,useMemo,useState} from 'react'
import {getSupabaseBrowserClient} from '../../lib/supabase'
const nav=[['Overview','⌂','/dashboard'],['Subjects','▱','/subjects'],['AI Tutor','✦','/ai-tutor'],['Mock Exams','□','/mock-exams'],['Daily Tasks','✓','/daily-tasks'],['Progress','↗','/progress']]
export default function MockExamsPage(){
 const [subjects,setSubjects]=useState([]),[subjectId,setSubjectId]=useState(''),[count,setCount]=useState(10),[exam,setExam]=useState(null),[questions,setQuestions]=useState([]),[answers,setAnswers]=useState({}),[review,setReview]=useState(null),[history,setHistory]=useState([]),[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[error,setError]=useState('')
 const selected=useMemo(()=>subjects.find(x=>x.id===subjectId),[subjects,subjectId])
 async function token(s){const {data}=await s.auth.getSession();if(data?.session?.access_token)return data.session.access_token;const r=await s.auth.refreshSession();if(!r.data?.session?.access_token)throw Error('Your login session has expired.');return r.data.session.access_token}
 useEffect(()=>{async function load(){const s=getSupabaseBrowserClient();if(!s){location.href='/login';return}const {data:{user}}=await s.auth.getUser();if(!user){location.href='/login';return}const a=await s.from('subjects').select('id,name').eq('user_id',user.id).order('created_at',{ascending:true});if(a.error)setError(a.error.message);else{setSubjects(a.data||[]);if(a.data?.[0])setSubjectId(a.data[0].id)}try{const t=await token(s),r=await fetch('/api/mock-exams',{headers:{Authorization:'Bearer '+t}}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Could not load history.');setHistory(j.exams||[])}catch(e){setError(e.message)}setLoading(false)}load()},[])
 async function generate(){if(!subjectId||working)return;setWorking(true);setError('');setReview(null);setExam(null);setAnswers({});try{const s=getSupabaseBrowserClient(),t=await token(s),r=await fetch('/api/mock-exams',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+t},body:JSON.stringify({subjectId,count})}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Could not generate the exam.');setExam(j.exam);setQuestions(j.questions||[]);scrollTo(0,0)}catch(e){setError(e.message)}finally{setWorking(false)}}
 async function submit(e){e.preventDefault();if(!exam||working)return;setWorking(true);setError('');try{const s=getSupabaseBrowserClient(),t=await token(s),payload=questions.map(q=>({position:q.position,answer:answers[q.position]||''})),r=await fetch('/api/mock-exams',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+t},body:JSON.stringify({action:'submit',examId:exam.id,answers:payload})}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Could not submit the exam.');setReview(j.review||[]);setExam(j.exam);const h=await fetch('/api/mock-exams',{headers:{Authorization:'Bearer '+t}}),hj=await h.json().catch(()=>({}));if(h.ok)setHistory(hj.exams||[]);scrollTo(0,0)}catch(e){setError(e.message)}finally{setWorking(false)}}
 const reset=()=>{setExam(null);setQuestions([]);setAnswers({});setReview(null);setError('');scrollTo(0,0)}
 if(loading)return <main className="shell dashboard-loading"><div className="loader-card"><div className="brand">TIA<span>LO</span></div><p>Loading your exams…</p></div></main>
 return <main className="dashboard-shell tialo-workspace"><aside className="sidebar"><a className="brand" href="/dashboard">TIA<span>LO</span></a><div className="sidebar-label">Workspace</div><nav className="sidebar-nav">{nav.map(([n,i,h])=><a className={'side-link '+(h==='/mock-exams'?'active':'')} href={h} key={h}><span>{i}</span>{n}</a>)}</nav><div className="sidebar-bottom"><a className="side-settings" href="/settings">⚙ Settings</a></div></aside><section className="dashboard-main"><header className="dashboard-topbar"><div><span className="topbar-title">Mock Exams</span><span className="topbar-dot">●</span><span className="muted">Practice from your material</span></div><a className="btn secondary" href="/materials">Materials</a></header><div className="dashboard-content mock-page">
 {!exam&&<><div className="workspace-intro"><div><div className="eyebrow">TIALO · MOCK EXAMS</div><h1>Practice with purpose.</h1><p>Build a focused multiple-choice exam from the material you have connected to a subject. Complete it, review every answer, and keep the result.</p></div><div className="workspace-chip"><span>●</span> Material grounded</div></div>{error&&<div className="notice">{error}</div>}<section className="exam-builder panel"><div className="builder-copy"><div className="section-kicker">BUILD AN EXAM</div><h2>Choose your session.</h2><p>Keep it short when you’re warming up. Go deeper when you’re ready.</p></div><div className="builder-controls"><label>Subject<select value={subjectId} onChange={e=>setSubjectId(e.target.value)} disabled={!subjects.length}>{!subjects.length&&<option>No subjects yet</option>}{subjects.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Length<select value={count} onChange={e=>setCount(Number(e.target.value))}><option value={5}>5 questions</option><option value={10}>10 questions</option><option value={15}>15 questions</option><option value={20}>20 questions</option></select></label><button className="btn primary" onClick={generate} disabled={!subjectId||working}>{working?'Building…':'Create exam'} <span>↗</span></button></div></section><section className="dashboard-section"><div className="section-heading"><div><div className="section-kicker">HISTORY</div><h2>Recent practice</h2><p>Every completed exam becomes part of your progress history.</p></div></div>{history.length?<div className="exam-history">{history.map(item=>{const pct=item.score==null?null:Math.round(item.score/item.total_marks*100);return <article className="history-row" key={item.id}><div className="history-index">□</div><div><strong>{item.title}</strong><span>{item.subjects?.name||'Subject'} · {new Date(item.created_at).toLocaleDateString()}</span></div><div className="history-score">{pct==null?'—':pct+'%'}<small>{item.score==null?'In progress':item.score+'/'+item.total_marks}</small></div></article>})}</div>:<div className="empty-state"><div className="empty-icon">□</div><h3>Your exam history starts here.</h3><p>Generate an exam above and your completed result will stay in this workspace.</p></div>}</section></>}
 {exam&&!review&&<section className="exam-session"><div className="workspace-intro"><div><div className="eyebrow">{selected?.name||'MOCK EXAM'}</div><h1>{exam.title}</h1><p>{questions.length} questions · one mark each · Choose the best answer.</p></div><div className="workspace-chip"><span>●</span> In progress</div></div>{error&&<div className="notice">{error}</div>}<form onSubmit={submit}><div className="question-list">{questions.map(q=><article className="question-card panel" key={q.id}><div className="question-meta"><span>QUESTION {q.position}</span><span>{answers[q.position]?'Answered':'Not answered'}</span></div><h2>{q.prompt}</h2><div className="options">{q.options.map((o,i)=>{const chosen=answers[q.position]===o;return <label className={'option '+(chosen?'chosen':'')} key={o}><input type="radio" name={'q'+q.position} checked={chosen} onChange={()=>setAnswers(a=>({...a,[q.position]:o}))}/><span className="option-letter">{String.fromCharCode(65+i)}</span><span>{o}</span></label>})}</div></article>)}</div><div className="exam-actions"><button type="button" className="btn secondary" onClick={reset}>Cancel</button><button className="btn primary" disabled={working}>{working?'Marking…':'Submit exam'} <span>↗</span></button></div></form></section>}
 {exam&&review&&<section className="exam-session"><div className="result-hero panel"><div><div className="eyebrow">EXAM COMPLETE</div><h1>{exam.title}</h1><p>Your result has been saved to your progress history.</p></div><div className="result-score"><strong>{exam.score}/{exam.total_marks}</strong><span>{Math.round(exam.score/exam.total_marks*100)}%</span></div></div>{error&&<div className="notice">{error}</div>}<div className="review-list">{review.map(item=><article className="review-card panel" key={item.id}><div className="question-meta"><span>QUESTION {item.position}</span><b className={item.correct?'correct':'incorrect'}>{item.correct?'CORRECT':'REVIEW'}</b></div><h2>{item.prompt}</h2><p>Your answer <strong>{item.student_answer||'Not answered'}</strong></p>{!item.correct&&<p>Correct answer <strong>{item.correct_answer}</strong></p>}{item.explanation&&<div className="explanation"><span>WHY</span>{item.explanation}</div>}</article>)}</div><button className="btn primary" onClick={reset}>Take another exam ↗</button></section>}
 </div></section></main>
}