'use client'

import { useEffect, useMemo, useState } from 'react'
import { getSupabaseBrowserClient } from '../../lib/supabase'

const nav=[['Overview','⌂','/dashboard'],['Subjects','▱','/subjects'],['AI Tutor','✦','/ai-tutor'],['Mock Exams','□','/mock-exams'],['Daily Tasks','✓','/daily-tasks'],['Progress','↗','/progress'],['Subscription','R','/billing']]
const dateKey=v=>new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v))
const calcAge=dob=>{if(!dob)return null;const d=new Date(`${dob}T00:00:00`),n=new Date();let a=n.getFullYear()-d.getFullYear();if(n.getMonth()<d.getMonth()||(n.getMonth()===d.getMonth()&&n.getDate()<d.getDate()))a--;return a}

export default function Dashboard(){
 const [user,setUser]=useState(null),[profile,setProfile]=useState(null),[subjects,setSubjects]=useState([]),[exams,setExams]=useState([]),[materials,setMaterials]=useState([]),[tasks,setTasks]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[mobile,setMobile]=useState(false)
 useEffect(()=>{async function load(){const s=getSupabaseBrowserClient();if(!s){location.href='/login';return}const {data:{user:u}}=await s.auth.getUser();if(!u){location.href='/login';return}const {data:p}=await s.from('profiles').select('full_name,date_of_birth,role').eq('id',u.id).maybeSingle();if(!p?.full_name||!p?.date_of_birth||!p?.role){location.href='/onboarding';return}if(p.role==='parent'&&calcAge(p.date_of_birth)>=18){location.href='/parent';return}if(p.role==='student'&&calcAge(p.date_of_birth)<16){const {data:l}=await s.from('parent_child').select('id').eq('child_id',u.id).eq('status','active').limit(1).maybeSingle();if(!l){location.href='/parent-link';return}}
 const [a,b,c,d]=await Promise.all([s.from('subjects').select('id,name,created_at').eq('user_id',u.id).order('created_at',{ascending:true}),s.from('exam_attempts').select('id,title,score,total_marks,status,completed_at,created_at,subjects(name)').eq('user_id',u.id).eq('status','completed').order('completed_at',{ascending:false}),s.from('materials').select('id,subject_id').eq('user_id',u.id),s.from('daily_study_tasks').select('id,title,completed,estimated_minutes,task_date,completed_at,subjects(name)').eq('user_id',u.id).order('task_date',{ascending:false})])
 setUser(u);setProfile(p);if(a.error)setError(a.error.message);else setSubjects(a.data||[]);setExams(b.data||[]);setMaterials(c.data||[]);setTasks(d.data||[]);setLoading(false)}load()},[])
 const first=profile?.full_name?.trim().split(/\s+/)[0]||'Student',done=tasks.filter(t=>t.completed),average=useMemo(()=>{const x=exams.filter(e=>Number(e.total_marks)>0).map(e=>Number(e.score||0)/Number(e.total_marks)*100);return x.length?Math.round(x.reduce((a,b)=>a+b,0)/x.length):null},[exams]),streak=useMemo(()=>{const x=new Set(done.map(t=>t.completed_at?dateKey(t.completed_at):t.task_date));let n=0,d=new Date();while(x.has(dateKey(d))){n++;d.setDate(d.getDate()-1)}return n},[done]),minutes=done.reduce((a,t)=>a+Number(t.estimated_minutes||0),0),focus=Math.min(100,Math.round(subjects.length*12+materials.length*4+done.length*2+(average||0)*.55))
 async function signOut(){const s=getSupabaseBrowserClient();await s?.auth.signOut();location.href='/'}
 if(loading)return <main className="shell dashboard-loading"><div className="loader-card"><div className="brand">TIA<span>LO</span></div><p>Preparing your workspace…</p></div></main>
 return <main className="dashboard-shell">
  {mobile&&<div className="mobile-nav-backdrop" style={{position:'fixed',inset:0,background:'rgba(0,0,0,.28)',zIndex:35}} onClick={()=>setMobile(false)}/>}
  <aside className="sidebar" style={mobile?{transform:'translateX(0)'}:undefined}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><a className="brand" href="/dashboard">TIA<span>LO</span></a><button className="sidebar-close" onClick={()=>setMobile(false)}>×</button></div><div className="sidebar-label">Workspace</div><nav className="sidebar-nav">{nav.map(([label,icon,href])=><a className={`side-link ${href==='/dashboard'?'active':''}`} href={href} key={href} onClick={()=>setMobile(false)}><span>{icon}</span>{label}</a>)}</nav><div className="sidebar-bottom"><div className="student-mini"><div className="avatar">{first[0]?.toUpperCase()}</div><div><strong>{first}</strong><span>Student workspace</span></div></div><a className="side-settings" href="/settings">⚙ Settings</a><button className="side-signout" onClick={signOut}>↪ Sign out</button></div></aside>
  <section className="dashboard-main"><header className="dashboard-topbar"><div className="topbar-left"><button onClick={()=>setMobile(true)} style={{display:'none',border:0,background:'none',fontSize:20,marginRight:10}}>☰</button><span className="topbar-title">Overview</span><span className="topbar-dot">●</span><span className="muted">Your academic workspace</span></div><div className="topbar-profile"><div><strong>{first}</strong><span>{user?.email}</span></div><div className="topbar-avatar">{first[0]?.toUpperCase()}</div></div></header>
   <div className="dashboard-content">
    <section className="dashboard-hero"><div><div className="eyebrow">{new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})}</div><h1>Make today<br/><em>count.</em></h1><p>Welcome back, {first}. Your workspace is ready. Choose one useful thing to do next and keep the session simple.</p><div className="actions"><a className="btn primary" href="/ai-tutor">Ask TIALO ↗</a><a className="btn secondary" href="/daily-tasks">Open today’s tasks</a></div></div><div className="hero-badge"><span>●</span> {streak?streak+' day streak':'Start your streak'}</div></section>
    {error&&<div className="notice" style={{marginTop:18}}>{error}</div>}
    <section className="dashboard-section dashboard-section-tight"><div className="section-heading"><div><div className="section-kicker">AT A GLANCE</div><h2>Your academic pulse</h2><p>A small set of numbers that actually matter.</p></div><span className="muted">LIVE</span></div><div className="stat-grid"><a className="stat-card" href="/subjects"><div className="stat-icon">▱</div><span>Subjects</span><strong>{subjects.length}</strong><small>In your workspace <b>→</b></small></a><a className="stat-card" href="/daily-tasks"><div className="stat-icon">✓</div><span>Tasks left</span><strong>{tasks.filter(t=>!t.completed).length}</strong><small>Daily study actions <b>→</b></small></a><a className="stat-card" href="/mock-exams"><div className="stat-icon">□</div><span>Mock exams</span><strong>{exams.length}</strong><small>Completed <b>→</b></small></a><a className="stat-card" href="/progress"><div className="stat-icon">↗</div><span>Average</span><strong>{average==null?'—':average+'%'}</strong><small>Completed exams <b>→</b></small></a></div></section>
    <section className="dashboard-section"><div className="section-heading"><div><div className="section-kicker">FOCUS</div><h2>Your study signal</h2><p>A quiet snapshot of consistency, not a score to chase.</p></div></div><div className="panel" style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) 190px',gap:30,alignItems:'center'}}><div><div style={{display:'flex',justifyContent:'space-between',fontSize:12,fontWeight:700}}><span>Workspace momentum</span><strong>{focus}%</strong></div><div style={{height:10,borderRadius:99,background:'#edf0eb',marginTop:12,overflow:'hidden'}}><div style={{height:'100%',width:`${focus}%`,background:'linear-gradient(90deg,#9fe870,#74c94b)',borderRadius:99}}/></div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:12,marginTop:22}}><div><strong>{minutes}</strong><div className="muted" style={{fontSize:10}}>study minutes</div></div><div><strong>{materials.length}</strong><div className="muted" style={{fontSize:10}}>materials</div></div><div><strong>{done.length}</strong><div className="muted" style={{fontSize:10}}>tasks completed</div></div></div></div><div style={{borderLeft:'1px solid var(--line)',paddingLeft:24}}><div className="section-kicker">NEXT STEP</div><h3>Keep it small.</h3><p className="muted" style={{fontSize:11,lineHeight:1.6}}>Finish one task, ask one good question, or practise one topic.</p><a href="/daily-tasks" style={{fontSize:11,fontWeight:800}}>Choose a task →</a></div></div></section>
    <section className="dashboard-section"><div className="section-heading"><div><div className="section-kicker">YOUR SUBJECTS</div><h2>Continue where you left off</h2><p>Your subjects are the foundation for every TIALO tool.</p></div><a className="btn secondary" href="/subjects">Manage subjects</a></div>{subjects.length===0?<div className="empty-state"><div className="empty-icon">▱</div><h3>Start with a subject</h3><p>Add your first subject and upload the material you want TIALO to work from.</p><a className="btn primary" href="/subjects" style={{marginTop:16}}>Add a subject</a></div>:<div className="subject-grid">{subjects.slice(0,6).map(s=>{const n=materials.filter(m=>m.subject_id===s.id).length;return <a className="subject-card" href="/subjects" key={s.id}><div className="subject-top"><span className="subject-icon">▱</span><span className="subject-arrow">→</span></div><h3>{s.name}</h3><p>{n} material{n===1?'':'s'} connected</p><div className="subject-progress"><span style={{width:n?'32%':'4%'}}/></div></a>})}</div>}</section>
    <section className="dashboard-section"><div className="section-heading"><div><div className="section-kicker">QUICK START</div><h2>What do you want to do?</h2><p>Jump straight into the part of TIALO you need.</p></div></div><div className="tool-grid"><a className="tool-card" href="/ai-tutor"><div className="tool-icon">✦</div><div><h3>Ask TIALO</h3><p>Guided explanations grounded in your study material.</p></div><span className="tool-status">Open →</span></a><a className="tool-card" href="/mock-exams"><div className="tool-icon">□</div><div><h3>Take a mock exam</h3><p>Turn your material into focused practice.</p></div><span className="tool-status">Open →</span></a><a className="tool-card" href="/daily-tasks"><div className="tool-icon">✓</div><div><h3>Plan today</h3><p>See the next study actions in your queue.</p></div><span className="tool-status">Open →</span></a><a className="tool-card" href="/progress"><div className="tool-icon">↗</div><div><h3>Review progress</h3><p>See your results and study history over time.</p></div><span className="tool-status">Open →</span></a></div></section>
    <div style={{marginTop:50,paddingTop:20,borderTop:'1px solid var(--line)',display:'flex',justifyContent:'space-between',gap:20,flexWrap:'wrap'}}><span className="muted" style={{fontSize:10}}>TIALO · Private academic workspace</span><span className="muted" style={{fontSize:10}}>Your data stays connected to your account.</span></div>
   </div>
  </section>
 </main>
}