'use client'
import {useEffect,useMemo,useState} from 'react'
import {getSupabaseBrowserClient} from '../../lib/supabase'

const nav=[['Overview','/dashboard'],['Subjects','/subjects'],['AI Tutor','/ai-tutor'],['Mock Exams','/mock-exams'],['Daily Tasks','/daily-tasks'],['Progress','/progress']]
const day=v=>new Date(v).toISOString().slice(0,10)
const age=dob=>{if(!dob)return null;const d=new Date(dob+'T00:00:00'),n=new Date();let a=n.getFullYear()-d.getFullYear();if(n.getMonth()<d.getMonth()||(n.getMonth()===d.getMonth()&&n.getDate()<d.getDate()))a--;return a}

export default function Dashboard(){
 const [user,setUser]=useState(null),[profile,setProfile]=useState(null),[subjects,setSubjects]=useState([]),[exams,setExams]=useState([]),[materials,setMaterials]=useState([]),[tasks,setTasks]=useState([]),[loading,setLoading]=useState(true),[mobile,setMobile]=useState(false),[error,setError]=useState('')
 useEffect(()=>{async function load(){const s=getSupabaseBrowserClient();if(!s){location.href='/login';return}const {data:{user:u}}=await s.auth.getUser();if(!u){location.href='/login';return}const {data:p}=await s.from('profiles').select('full_name,date_of_birth,role').eq('id',u.id).maybeSingle();if(!p?.full_name||!p?.date_of_birth||!p?.role){location.href='/onboarding';return}if(p.role==='parent'&&age(p.date_of_birth)>=18){location.href='/parent';return}if(p.role==='student'&&age(p.date_of_birth)<16){const {data:l}=await s.from('parent_child').select('id').eq('child_id',u.id).eq('status','active').limit(1).maybeSingle();if(!l){location.href='/parent-link';return}}
 const [a,b,c,d]=await Promise.all([s.from('subjects').select('id,name').eq('user_id',u.id).order('created_at',{ascending:true}),s.from('exam_attempts').select('id,title,score,total_marks,completed_at,subjects(name)').eq('user_id',u.id).eq('status','completed').order('completed_at',{ascending:false}).limit(12),s.from('materials').select('id,subject_id').eq('user_id',u.id),s.from('daily_study_tasks').select('id,title,completed,estimated_minutes,task_date,completed_at,subjects(name)').eq('user_id',u.id).order('task_date',{ascending:true})]);setUser(u);setProfile(p);setSubjects(a.data||[]);setExams(b.data||[]);setMaterials(c.data||[]);setTasks(d.data||[]);if(a.error||b.error||c.error||d.error)setError('Some workspace data is still loading.');setLoading(false)}load()},[])
 const first=profile?.full_name?.trim().split(/\s+/)[0]||'Student'
 const pending=tasks.filter(t=>!t.completed),done=tasks.filter(t=>t.completed)
 const average=useMemo(()=>{const x=exams.filter(e=>Number(e.total_marks)>0).map(e=>Number(e.score||0)/Number(e.total_marks)*100);return x.length?Math.round(x.reduce((a,b)=>a+b,0)/x.length):null},[exams])
 const streak=useMemo(()=>{const days=new Set(done.map(t=>t.completed_at?day(t.completed_at):t.task_date));let n=0,d=new Date();while(days.has(day(d))){n++;d.setDate(d.getDate()-1)}return n},[done])
 const chart=useMemo(()=>exams.slice().reverse().slice(-7),[exams])
 async function signOut(){const s=getSupabaseBrowserClient();await s?.auth.signOut();location.href='/'}
 if(loading)return <main className="new-loading"><div className="new-logo">TIA<span>LO</span></div><span>Opening your workspace…</span></main>
 return <main className="tialo-new-shell">
  <aside className={'new-sidebar '+(mobile?'open':'')}><div className="new-sidebar-top"><a className="new-logo" href="/dashboard">TIA<span>LO</span></a><button onClick={()=>setMobile(false)}>×</button></div><div className="new-nav-label">Workspace</div><nav>{nav.map(([label,href])=><a className={href==='/dashboard'?'selected':''} href={href} key={href}><span>{label}</span>{href==='/daily-tasks'&&pending.length>0?<b>{pending.length}</b>:null}</a>)}</nav><div className="new-sidebar-bottom"><div className="new-user"><div>{first[0]?.toUpperCase()}</div><span>{first}</span></div><button onClick={signOut}>Sign out</button></div></aside>
  {mobile&&<div className="new-backdrop" onClick={()=>setMobile(false)}/>}
  <section className="new-main">
   <header className="new-header"><button className="new-menu" onClick={()=>setMobile(true)}>☰</button><div><strong>Overview</strong><span> / {new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</span></div><div className="new-header-user">{first}<div>{first[0]?.toUpperCase()}</div></div></header>
   <div className="new-content">
    <section className="welcome-row"><div><div className="new-kicker">GOOD MORNING, {first.toUpperCase()}</div><h1>What are you<br/><i>working on?</i></h1><p>Pick one thing. TIALO will help you make progress without the noise.</p></div><a className="new-primary" href="/ai-tutor">Ask TIALO <span>↗</span></a></section>
    {error&&<div className="new-notice">{error}</div>}
    <section className="today-grid">
      <div className="today-main"><div className="new-kicker">UP NEXT</div><h2>{pending[0]?.title||'You are all caught up.'}</h2><p>{pending[0]?((pending[0].subjects?.name||'Study session')+' · '+(pending[0].estimated_minutes||15)+' min'): 'Choose a subject or ask TIALO something new.'}</p><div className="today-actions">{pending[0]&&<a className="new-primary small" href="/daily-tasks">Continue →</a>}<a className="new-ghost" href="/subjects">Browse subjects</a></div></div>
      <div className="today-side"><div className="today-number">{streak}</div><span>day{streak===1?'':'s'} in a row</span><div className="mini-dots">{[0,1,2,3,4,5,6].map(i=><i className={i<Math.min(streak,7)?'on':''} key={i}/>)}</div></div>
    </section>
    <section className="dashboard-block"><div className="block-head"><div><div className="new-kicker">YOUR SUBJECTS</div><h2>Continue learning</h2></div><a href="/subjects">View all →</a></div>{subjects.length?<div className="new-subject-grid">{subjects.slice(0,4).map(s=>{const count=materials.filter(m=>m.subject_id===s.id).length;return <a className="new-subject" href="/subjects" key={s.id}><span>{String(s.name).slice(0,2).toUpperCase()}</span><h3>{s.name}</h3><p>{count} material{count===1?'':'s'} connected</p><div><i style={{width:count?'42%':'8%'}}/></div></a>})}</div>:<div className="new-empty">Add your first subject to start building your study space. <a href="/subjects">Add subject →</a></div>}</section>
    <section className="insight-grid">
      <article className="insight-card performance"><div className="block-head"><div><div className="new-kicker">PERFORMANCE</div><h2>Recent exam scores</h2></div><strong>{average==null?'—':average+'%'}</strong></div>{chart.length?<div className="new-chart"><svg viewBox="0 0 700 190" preserveAspectRatio="none"><line x1="0" y1="165" x2="700" y2="165"/><line x1="0" y1="85" x2="700" y2="85"/><polyline points={chart.map((e,i)=>{const x=10+(680*i/Math.max(1,chart.length-1)),y=165-(Math.max(0,Math.min(100,Number(e.score||0)/Math.max(1,Number(e.total_marks))*100))/100)*130;return x+','+y}).join(' ')}/>{chart.map((e,i)=>{const x=10+(680*i/Math.max(1,chart.length-1)),y=165-(Math.max(0,Math.min(100,Number(e.score||0)/Math.max(1,Number(e.total_marks))*100))/100)*130;return <circle key={i} cx={x} cy={y} r="4"/>})}</svg><div className="chart-labels">{chart.map((e,i)=><span key={i}>{i===0||i===chart.length-1?new Date(e.completed_at).toLocaleDateString(undefined,{day:'numeric',month:'short'}):''}</span>)}</div></div>:<div className="new-empty">Complete a mock exam and your results will appear here.</div>}</article>
      <article className="insight-card"><div className="new-kicker">ACTIVITY</div><h2>This week</h2><div className="activity-stat"><strong>{done.reduce((a,t)=>a+Number(t.estimated_minutes||0),0)}</strong><span>study minutes</span></div><div className="activity-row"><span>{done.length} tasks completed</span><span>{pending.length} remaining</span></div><a href="/progress">See full progress →</a></article>
    </section>
    <section className="tool-strip"><a href="/ai-tutor"><b>✦</b><span><strong>Ask TIALO</strong><small>Get an explanation</small></span><i>→</i></a><a href="/mock-exams"><b>□</b><span><strong>Mock exam</strong><small>Test what you know</small></span><i>→</i></a><a href="/daily-tasks"><b>✓</b><span><strong>Today's tasks</strong><small>{pending.length} waiting for you</small></span><i>→</i></a></section>
   </div>
  </section>
 </main>
}
